// <auto-generated />
using System;
using FlowerStore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowerStore.Infrastructure.Migrations
{
    [DbContext(typeof(FlowerStoreDbContext))]
    [Migration("20241204131502_RemovedRequiredValidationsAndOverridePhoneField")]
    partial class RemovedRequiredValidationsAndOverridePhoneField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Cart.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Cart identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductsCounter")
                        .HasMaxLength(15)
                        .HasColumnType("int")
                        .HasComment("Count of products in cart");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Cart total price");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User's Identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Carts.ShoppingCartProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int")
                        .HasComment("Cart identifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of product");

                    b.Property<int>("Quantity")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasComment("Quantity of product");

                    b.HasKey("ShoppingCartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartsProducts");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Category identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Name of category");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tropical"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desert"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Indoor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Outdoor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wildflowers"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Exotic"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Native"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Seasonal"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Orders.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CardDetailsId")
                        .HasColumnType("int")
                        .HasComment("Card identifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("First name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Last name");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasComment("Order date");

                    b.Property<string>("OrderDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("More details of the order");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int")
                        .HasComment("Order status identifier");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasComment("Chosen payment identifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Phone number");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Shipping address");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int")
                        .HasComment("Shopping Cart identifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Payment amount");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.HasIndex("CardDetailsId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShoppingCartId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Orders.Order.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("Order identifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of product");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Product name");

                    b.Property<int>("Quantity")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasComment("Quantity of product");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrdersProducts");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Orders.Order.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order status identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("OrderStatusName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Name of the order status");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderStatusName = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            OrderStatusName = "Shipped"
                        },
                        new
                        {
                            Id = 3,
                            OrderStatusName = "Delivered"
                        });
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Payment.CardDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Card identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasComment("Code of Card Verification Value");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("First and last name of holder");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComment("Card number");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("Card's expiration date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.ToTable("CardDetails");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Payment.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Chosen payment idenfitier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Payment option name");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Card"
                        });
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Availability")
                        .HasColumnType("bit")
                        .HasComment("Indicator for in stock/out of stock");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("Category identifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasComment("Product add date");

                    b.Property<int>("FlowersCount")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasComment("Counter of product in stock");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasComment("Product description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Product image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Product name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of product");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4758),
                            FlowersCount = 5,
                            FullDescription = "The rose is a classic symbol of love and beauty, known for its exquisite fragrance and delicate petals. This beautiful flower comes in various colors, with the red rose being the most iconic symbol of romance. Our roses are carefully cultivated to ensure freshness and quality. In the tapestry of botanical history, the Red Rose emerges as a symbol of passion, romance, and enduring love. Its origins are steeped in ancient lore, tracing back to the verdant gardens of Persia, where its scarlet petals first unfurled beneath the gaze of starlit skies. Legends speak of goddesses and mortal admirers alike, captivated by the velvety allure and intoxicating fragrance of this timeless bloom. The Red Rose, with its velvety crimson petals, symbolizes the fervent flames of love and desire. Its rich hue evokes the blush of a lover's cheek and the ardor of a heart aflame. From clandestine rendezvous to grand declarations, the Red Rose has enraptured souls throughout the ages, transcending boundaries of time and culture with its timeless allure.",
                            ImageUrl = "https://img.freepik.com/premium-photo/red-roses-pot-isolated-white-background_511010-2090.jpg",
                            Name = "Rose",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            CategoryId = 7,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4759),
                            FlowersCount = 7,
                            FullDescription = "The elusive Blue Orchid, with its captivating hue, whispers tales of ancient mystique and ethereal beauty. Legend has it that this rare bloom emerged from the depths of forgotten realms, its petals kissed by moonlight and tears of the gods. Its enchanting color, a symphony of cobalt and azure, reflects the secrets of the universe, beckoning admirers into a world of wonder and enchantment. Unlike its vibrant counterparts, the Blue Orchid owes its unique coloration to a delicate balance of genetic mutation and environmental alchemy. Through a serendipitous interplay of genetic expression and environmental factors, this majestic flower dons its celestial cloak, inviting awe and admiration from all who behold its splendor.",
                            ImageUrl = "https://i.pinimg.com/736x/3e/14/88/3e148876fc1b8d1b4063a6695a7ebc9a.jpg",
                            Name = "Blue Orchid",
                            Price = 17.50m
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            CategoryId = 7,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4760),
                            FlowersCount = 4,
                            FullDescription = "Deep within the lush rainforests of West Africa, the majestic Ficus Lyrata, known colloquially as the Fiddle Leaf Fig, reigns as a verdant monarch of the jungle. Its origins intertwine with the ancient rhythms of the forest, where sunlight dances through emerald canopies and gentle rains nurture the soil. Born from the earth's embrace and nurtured by the whispers of the wind, the Ficus Lyrata embodies the resilience and grace of its tropical homeland. The Fiddle Leaf Fig derives its moniker from the lyrical curvature of its expansive leaves, which resemble the graceful silhouette of a fiddle or violin. Each leaf unfurls with a symphony of green hues, invoking a sense of harmony and tranquility in any space it inhabits. From its ancestral roots to its contemporary allure, the Ficus Lyrata remains a cherished emblem of natural beauty and botanical elegance.",
                            ImageUrl = "https://cdn.webshopapp.com/shops/30495/files/448237057/ficus-lyrata-xl-fiddle-leaf-fig-pot-21cm-height-80.jpg",
                            Name = "Ficus Lyrata",
                            Price = 22.30m
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            CategoryId = 4,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4760),
                            FlowersCount = 5,
                            FullDescription = "Tagetes, commonly known as marigold, is a genus of flowering plants in the family Asteraceae. These vibrant flowers are native to North and South America but are widely cultivated around the world for ornamental, medicinal, and culinary purposes. Tagetes flowers are typically yellow, orange, or red, often with ruffled or double-petaled blooms. They range in size from small pom-poms to larger, more dramatic heads. They are usually annuals but can sometimes be perennial, depending on the species. Tagetes grows in a bushy habit and varies in size, from compact dwarf varieties to taller plants over a meter high. ",
                            ImageUrl = "https://skgarden.bg/media/18/326.jpg",
                            Name = "Orange Tagetes",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4761),
                            FlowersCount = 10,
                            FullDescription = "Begonias are a diverse genus of flowering plants in the family Begoniaceae, encompassing over 2,000 species. They are prized for their vibrant flowers, striking foliage, and adaptability to various growing conditions. Native to tropical and subtropical regions worldwide, begonias are cultivated extensively as ornamental plants. They produce showy flowers in a range of colors, including red, pink, white, and orange. The blooms are often asymmetrical and can vary significantly in size depending on the variety.",
                            ImageUrl = "https://skgarden.bg/media/18/160.jpg",
                            Name = "Pink Begonia",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4762),
                            FlowersCount = 10,
                            FullDescription = "Begonias are a diverse genus of flowering plants in the family Begoniaceae, encompassing over 2,000 species. They are prized for their vibrant flowers, striking foliage, and adaptability to various growing conditions. Native to tropical and subtropical regions worldwide, begonias are cultivated extensively as ornamental plants. They produce showy flowers in a range of colors, including red, pink, white, and orange. The blooms are often asymmetrical and can vary significantly in size depending on the variety.",
                            ImageUrl = "https://skgarden.bg/media/18/158.jpg",
                            Name = "Red Begonia",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            CategoryId = 3,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4762),
                            FlowersCount = 4,
                            FullDescription = "The white anthurium, often called the peace lily anthurium or white flamingo flower, is a striking plant known for its elegant white flowers and glossy green leaves. Belonging to the genus Anthurium within the family Araceae, this tropical plant is prized for its ornamental value and ease of care. The \"flower\" is actually a spathe, a modified leaf, typically white or off-white, surrounding a yellow or pale green spadix. Its minimalist aesthetic makes it a popular choice for modern interiors. These plants grow as evergreen perennials, reaching heights of 12–24 inches (30–60 cm) depending on the species or variety.",
                            ImageUrl = "https://www.greenthumb.com/wp-content/uploads/2022/10/c6154cf6-cd75-5a1b-99be-d8e97dc6b45b_455bd0bd-8b8f-430f-a309-baaafe792f1b.jpg",
                            Name = "White Anthurium",
                            Price = 24.00m
                        },
                        new
                        {
                            Id = 8,
                            Availability = true,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4763),
                            FlowersCount = 8,
                            FullDescription = "The yellow begonia is a radiant and cheerful flowering plant belonging to the genus Begonia in the family Begoniaceae. It is loved for its bright yellow blooms, lush foliage, and versatility in gardening. Native to tropical and subtropical regions, begonias have been cultivated worldwide for their ornamental beauty. The blooms are a vivid yellow, often large and lush, with single or double petals depending on the variety. The flowers create a striking contrast against the green leaves. Yellow begonias can grow as upright or trailing plants, depending on the species. They are compact and bushy, making them perfect for small spaces or containers.",
                            ImageUrl = "https://www.provenwinners.com/sites/provenwinners.com/files/imagecache/low-resolution/ifa_upload/begonia_solenia_yellow_mono.jpg",
                            Name = "Yellow Begonia",
                            Price = 8.00m
                        },
                        new
                        {
                            Id = 9,
                            Availability = true,
                            CategoryId = 4,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4763),
                            FlowersCount = 12,
                            FullDescription = "The pink geranium, belonging to the genus Pelargonium in the family Geraniaceae, is a beloved flowering plant known for its vibrant pink blooms and aromatic foliage. Native to South Africa, geraniums are widely cultivated as ornamentals in gardens, pots, and hanging baskets. Pink geraniums produce clusters of five-petaled flowers in various shades of pink, from pastel to bright hues. The flowers often have subtle patterns or darker streaks, adding depth and visual interest. These plants are profuse bloomers, flowering from spring to late autumn in the right conditions.",
                            ImageUrl = "https://flower.bigbadmole.com/wp-content/uploads/2019/12/1-zaglavnaja-3.jpg",
                            Name = "Pink Geranium",
                            Price = 5.80m
                        },
                        new
                        {
                            Id = 10,
                            Availability = true,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4764),
                            FlowersCount = 6,
                            FullDescription = "The purple ageratum, commonly known as floss flower, is a charming and hardy annual plant in the family Asteraceae. Its botanical name is typically Ageratum houstonianum, and it is prized for its fluffy, soft-textured flowers that resemble tufts of thread or floss. Native to Central America and Mexico, purple ageratum is widely grown for its vibrant purple blooms and easy maintenance. Purple ageratum grows in compact mounds, typically reaching heights of 6–12 inches (15–30 cm), depending on the variety. It is a prolific bloomer, flowering continuously from late spring to the first frost in fall.",
                            ImageUrl = "https://skgarden.bg/media/18/369.jpg",
                            Name = "Purple Ageratum",
                            Price = 9.30m
                        },
                        new
                        {
                            Id = 11,
                            Availability = true,
                            CategoryId = 4,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4764),
                            FlowersCount = 14,
                            FullDescription = "The red geranium, a popular variant of the Pelargonium genus in the Geraniaceae family, is admired for its vibrant, long-lasting red blooms and attractive foliage. Native to South Africa, red geraniums are widely cultivated around the world for their ornamental appeal, easy maintenance, and versatility. The bold red flowers grow in clusters atop sturdy stems. The blooms range in shades from bright scarlet to deep crimson and are excellent for adding dramatic color to gardens. Red geraniums can grow upright, spreading, or trailing, making them versatile for beds, borders, containers, and hanging baskets. Plants typically reach heights of 12–24 inches (30–60 cm).",
                            ImageUrl = "https://dfwmnhok7ak0p.cloudfront.net/91919/V21964/C/1691650160000/1280.jpg",
                            Name = "Red Geranium",
                            Price = 5.80m
                        },
                        new
                        {
                            Id = 12,
                            Availability = true,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4765),
                            FlowersCount = 15,
                            FullDescription = "Pink petunias are flowering plants in the genus Petunia, belonging to the family Solanaceae. Known for their trumpet-shaped blooms and vibrant hues, pink petunias are versatile and widely loved for their ability to thrive in various settings. These annuals or tender perennials (in warmer climates) are native to South America. Pink petunias produce abundant, trumpet-shaped flowers in soft pastel, bright, or even patterned pink shades. Some varieties are fragrant, particularly in the evening. Petunias can be upright or trailing, depending on the variety. They typically grow 6–18 inches (15–45 cm) tall and spread up to 24 inches (60 cm).",
                            ImageUrl = "https://skgarden.bg/media/18/420.jpg",
                            Name = "Pink Petunias",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 13,
                            Availability = true,
                            CategoryId = 6,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4765),
                            FlowersCount = 4,
                            FullDescription = "Pelargonium within the family Geraniaceae. It is a vibrant and showy ornamental plant, prized for its lush purple flowers and fragrant, lobed foliage. Native to South Africa, pelargoniums have become globally popular in gardens and pots for their vivid colors and adaptability. The blooms of purple pelargonium are typically rich in color, ranging from soft lavender to deep purple. The flowers are often multi-toned, with darker markings or streaks on the petals, adding an artistic flair. Depending on the variety, purple pelargoniums can grow upright or exhibit a trailing habit, making them suitable for containers, hanging baskets, and garden beds. They typically grow 12–24 inches (30–60 cm) tall.",
                            ImageUrl = "https://skgarden.bg/media/18/436.jpg",
                            Name = "Purple Pelargonium",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 14,
                            Availability = true,
                            CategoryId = 4,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4766),
                            FlowersCount = 9,
                            FullDescription = "The white geranium is a striking variant of the Pelargonium genus, a flowering plant in the Geraniaceae family. Known for its pristine white blooms, it’s a popular ornamental plant used in gardens, hanging baskets, and containers. Native to South Africa, geraniums (including white varieties) have been cultivated for their beauty, fragrance, and ease of care. The white geranium produces elegant, pure white flowers, often with subtle markings or veins in the center of each petal. These flowers are typically five-petaled and appear in clusters atop sturdy stems. White geraniums can grow upright or trailing, making them versatile for garden beds, containers, hanging baskets, and window boxes. They usually grow between 12 to 18 inches (30 to 45 cm) in height, depending on the variety.",
                            ImageUrl = "https://skgarden.bg/media/18/206.jpg",
                            Name = "White Geranium",
                            Price = 6.70m
                        },
                        new
                        {
                            Id = 15,
                            Availability = true,
                            CategoryId = 1,
                            DateAdded = new DateTime(2024, 12, 4, 13, 15, 2, 168, DateTimeKind.Utc).AddTicks(4767),
                            FlowersCount = 3,
                            FullDescription = "The pink hibiscus is a tropical flowering plant belonging to the genus Hibiscus, part of the Malvaceae family. Known for its large, showy blooms and vibrant pink color, this plant is often associated with tropical and subtropical regions around the world. Pink hibiscus is widely cultivated for its striking appearance and symbolic meanings of beauty, femininity, and exoticism. The flowers of pink hibiscus are large, with five petals that can range from soft pastels to vibrant pinks. Some varieties feature darker veins or a contrasting center, making them visually captivating. These flowers can be up to 6 inches (15 cm) in diameter and are often funnel-shaped. Pink hibiscus plants can grow as shrubs, bushes, or small trees, reaching heights of 3–10 feet (1–3 meters), depending on the species and growing conditions. They can have a bushy, rounded shape with a thick, woody trunk.",
                            ImageUrl = "https://photo.floraccess.com/5g5qcbeu7okodcmedk0m43tl9shnbbgm245af2bd_Preview480.jpg",
                            Name = "Pink Hibiscus",
                            Price = 32.00m
                        });
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Review identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Content of review");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Creation date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Fast delivery and excellent quality. Will buy again for sure!!!",
                            CreatedAt = new DateTime(2024, 12, 4, 15, 15, 2, 153, DateTimeKind.Local).AddTicks(7352),
                            UserId = "e50f5dc0-298d-4807-88f0-73b88c82e128"
                        },
                        new
                        {
                            Id = 2,
                            Content = "The customer service was exceptional! They were very responsive and helped me choose the perfect arrangement. I’ll definitely be ordering again soon.",
                            CreatedAt = new DateTime(2024, 12, 4, 15, 15, 2, 153, DateTimeKind.Utc).AddTicks(7355),
                            UserId = "9a53e015-990d-4cd0-ae04-2d402060c207"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Fast, efficient, and elegant! The flowers were in pristine condition, and the little card included was a nice touch. Amazing experience overall.",
                            CreatedAt = new DateTime(2024, 12, 4, 17, 15, 2, 153, DateTimeKind.Utc).AddTicks(7356),
                            UserId = "e50f5dc0-298d-4807-88f0-73b88c82e128"
                        });
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("First name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Last name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Phone number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a21722de-a984-476a-a7d7-8e48dadde907",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81a4099a-d91d-47c4-a69f-254955f02d7d",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDLJYHYwzo9YAe7ACDfJuOr+JeaHQQaRNM3jBiwYgNmWNXZj5EURJB712IbR/JDy/A==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b281533a-43e1-4378-bd4f-7ce3e23ba057",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        },
                        new
                        {
                            Id = "e50f5dc0-298d-4807-88f0-73b88c82e128",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "075e8f29-8994-4fc1-bbfa-743358055f59",
                            Email = "guest@guest.com",
                            EmailConfirmed = false,
                            FirstName = "Guest",
                            LastName = "Guest",
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST@GUEST.COM",
                            NormalizedUserName = "GUEST@GUEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEI6C35t4pzYm3GtSFkJbMiBEFsGnKhFvxiB9kpVD8EbCDzbzW8ENdLxDaXD7ifpJzQ==",
                            PhoneNumber = "1234567800",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6de2f3d2-ab3b-4611-8310-d95ea81ac07d",
                            TwoFactorEnabled = false,
                            UserName = "guest@guest.com"
                        },
                        new
                        {
                            Id = "9a53e015-990d-4cd0-ae04-2d402060c207",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d11bf9bd-0e64-46db-9e56-19c592e99b4d",
                            Email = "test@test.com",
                            EmailConfirmed = false,
                            FirstName = "Test",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@TEST.COM",
                            NormalizedUserName = "TEST@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELxpAbm7EPdbn6xuvkrY2lE0VsAiQKiZz4PuJ8tJs92OotgrkbXLJZvLv29JYcHFYQ==",
                            PhoneNumber = "1234567700",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "69a68a09-706b-4a77-9c05-7af82fa25c9b",
                            TwoFactorEnabled = false,
                            UserName = "test@test.com"
                        },
                        new
                        {
                            Id = "d5f40bd1-8e34-4354-8996-0f884be97351",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f23bdbc-8f5c-4fca-b0f8-e7b7ef7c6085",
                            Email = "random@random.com",
                            EmailConfirmed = false,
                            FirstName = "Random",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "RANDOM@RANDOM.COM",
                            NormalizedUserName = "RANDOM@RANDOM.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIkBsiSun/ckFAje165ps9HPdDdflwMJ5/BjwL3eaHoMHZKA9RWHe9RWm8m7syGyGA==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45c46195-ea4e-4a9d-ab50-b15fc486f761",
                            TwoFactorEnabled = false,
                            UserName = "random@random.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "user:fullname",
                            ClaimValue = "Admin Admin",
                            UserId = "a21722de-a984-476a-a7d7-8e48dadde907"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "user:fullname",
                            ClaimValue = "Guest Guest",
                            UserId = "e50f5dc0-298d-4807-88f0-73b88c82e128"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "user:fullname",
                            ClaimValue = "Test Test",
                            UserId = "9a53e015-990d-4cd0-ae04-2d402060c207"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "user:fullname",
                            ClaimValue = "Random User",
                            UserId = "d5f40bd1-8e34-4354-8996-0f884be97351"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Cart.ShoppingCart", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Carts.ShoppingCartProduct", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Cart.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartProducts")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Orders.Order.Order", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Payment.CardDetails", "CardDetails")
                        .WithMany()
                        .HasForeignKey("CardDetailsId");

                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Orders.Order.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Payment.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Cart.ShoppingCart", "ShoppingCart")
                        .WithMany()
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardDetails");

                    b.Navigation("OrderStatus");

                    b.Navigation("PaymentMethod");

                    b.Navigation("ShoppingCart");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Orders.Order.OrderProduct", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Orders.Order.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Cart.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartProducts");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Orders.Order.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("FlowerStore.Infrastructure.Data.Models.Roles.ApplicationUser", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
